### ISSUE TITLE
Error in MEI for Salzinnes 001v

### ISSUE THREAD

**Issue by dchiller** [DDMAL/e2e-omr-resources#13]
I've found what looks to be an error in the reviewed MEI for Salzinnes 001v. [Here's a link to that image on CU](https://cantus.simssa.ca/manuscript/123723/?folio%5B0%5D=001v&pageAlias=Folio%20001v)...the place in question is on the 7th line, beginning with the chant "Ecce venit"

https://github.com/DDMAL/e2e-omr-resources/blob/6bf029f76589fcddbac5555e63be4b5c5e8196a8/resulting_mei_files/Salzinnes/reviewed/CDN-Hsmu_M2149.L4_001v.mei#L901-L928

It looks like everything on that staff 7 is encoded down a third from where it should be ... am I reading that right? Could it be because the clef on that line doesn't get encoded?

@annamorphism @JoyfulGen 

Not meaning to be pedantic or catch every little possible mistake but noticed this because of an unrelated error in MEI search on CU and got worried because of the other C-clef issues we've been having that this might be related :(

**Comment by annamorphism** [comment]
Interesting...looking at the file, it seems there is a clef on line 6 at position -3. It seems to be throwing off the octave for the remainder of line 6 and then also messing up line 7. Let's hope it's a one-off error from this early folio...

**Comment by JoyfulGen** [comment]
The problem is that the clef for line 7 was mistakenly associated to the staff above (hence the position -3 that Anna noticed). So line 7 effectively didn't have a clef, which means that the pitches were being determined by the default clef position on line 1. Hence the third too low! We had issues like this quite a bit at the beginning, because we weren't always in the habit of checking if staff associations were always correct. I'm sure it's not connected to the octave displacement issues!

I've fixed the problem and re-uploaded the file to github. @dchiller could you have a look to confirm it all looks good now?

These treasure hunts are quite fun :)

**Comment by dchiller** [comment]
Looks correct to me now! Good to know it's probably not connected to the larger issues. :) I'll close this now, then...

Thanks for the investigation @JoyfulGen and @annamorphism
